---
PreCommit:
  TrailingWhitespace:
    enabled: true
  YamlLint:
    enabled: true
  ChefSpec:
    enabled: true
    command: ["chef", "exec", "rspec"]
    include: ["**/*.rb"]
  Cookstyle:
    enabled: true
    required_executable: "cookstyle"
    command: ["cookstyle"]
    include: ["**/*.rb"]
  MarkdownLint:
    enabled: true
    command: ["npx", "markdownlint-cli2", "'**/*.md'"]
    include: ["**/*.md"]
CommitMsg:
  HardTabs:
    enabled: true
