maintainer 'Eric G. Wolfe'
maintainer_email 'eric.wolfe@gmail.com'
license 'Apache-2.0'
description 'Installs and configures NFS, and NFS exports'
name 'nfs'
version '2.6.4'
source_url 'https://github.com/atomic-penguin/cookbook-nfs'
issues_url 'https://github.com/atomic-penguin/cookbook-nfs/issues'
chef_version '>= 13.0'

supports 'ubuntu', '>= 16.04'
supports 'debian', '>= 8.0'
supports 'centos', '>= 6.8'
supports 'redhat', '>= 6.8'
supports 'scientific', '>= 6.8'
supports 'oracle', '>= 6.8'
supports 'suse', '>= 11.1'

depends 'line', '>= 2.0'
